#!/bin/ksh
test -f .SsmDepot && SsmDepot=$(cat .SsmDepot)
SsmDepot=${SsmDepot:-/data/armnraid1/www/ssm}
package=${0#./}
package=${package%%/*}
echo package=$package
TarCmd="echo tar"
tar --help 1>/dev/null && TarCmd=tar
gtar --help 1>/dev/null && TarCmd=gtar
gnutar --help 1>/dev/null && TarCmd=gnutar
set -x
${TarCmd} $(cat code-tools_1.0_all/maint/excludes) --exclude-from=code-tools_1.0_all/maint/excludes.list -zcf ${SsmDepot}/${package}.ssm $(cat code-tools_1.0_all/maint/include)
